print("Informe o nome do aluno: ")
aluno = input ()
print("Idade do aluno: ")
idade = input ()
print(" ")
print("Informe as notas a seguir:  ")
print(" ")
print("Nota 1 : ")
nota1 = float( input ())
print("Nota 2 : ")
nota2 = float(input ())
print("Nota 3 : ")
nota3 = float(input ())
print("Nota 4 : ")
nota4 = float(input ())

media = (nota1+nota2+nota3+nota4)/4

print ("aluno ", aluno)
print ("Idade: ", idade)
print ("Primeiro bimestre: ", nota1)
print ("Segundo bimestre: ", nota2)
print ("Terceiro bimestre: ", nota3)
print ("Quarto bimestre: ", nota4)
print ("Sua Média anual foi: ", media)