valor1 = int(input("Digite um valor: "))
valor2 = int(input("Digite um valor: "))
valor3 = int(input("Digite um valor: "))

if valor1 > valor2 and valor1>valor3 :
        print("\nO MAIOR VALOR DIGITADO FOI: ", valor1)
elif valor2 > valor1 and valor2>valor3 :
        print("\nO MAIOR VALOR DIGITADO FOI: ", valor2)
elif valor3 > valor1 and valor3>valor2 :
        print("\nO MAIOR VALOR DIGITADO FOI: ", valor3)
